service: quiz-app16
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1 
  environment:
    COGNITO_USER_POOL_ID: !Ref UserPool
    COGNITO_CLIENT_ID:  !Ref UserPoolClient
    table_name: !Ref quizTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:SignUp
        - cognito-idp:ConfirmSignUp
        - cognito-idp:AdminCreateUse
        - cognito-idp:AdminConfirmSignUp
      Resource: arn:aws:cognito-idp:ap-south-1:594264654627:userpool/ap-south-1_oMWDjn0y7


    

functions:
  createQuiz:
    handler: handler.createQuiz
    environment:
      QUIZ_TABLE_NAME: !Ref quizTable

    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt quizTable.Arn
    events:
      - http:
          method: post
          path: Quiz

  getallQuiz:
    handler: handler.getallQuiz
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:Scan
        Resource: !GetAtt quizTable.Arn 
    events:
      - http:
          path: Quiz
          method: get
          cors: true         

  userSignUp:
    handler: userSignup.handler
    events:
      - http:
          method: post
          path: user/signup 


  userSignupConfirmation: 
    handler: confirmUser.handler
    events:
      - http:
          path: user/confirmsignup
          method: post
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ConfirmSignUp
        Resource: arn:aws:cognito-idp:ap-south-1:594264654627:userpool/ap-south-1_oMWDjn0y7

  loginUser:
    handler: userSignIn.handler
    events:
      - http:
          path: user/login
          method: post






plugins:
  - serverless-iam-roles-per-function  

resources:
  Resources:
    quizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Quiz-app16db
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH

    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: quiz-16,
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT        
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
            Mutable: true
            #name
          - Name: name
            Required: true
            Mutable: true
            #phonenumber         
          - Name: phone_number
            Required: true
            Mutable: true
            #location
          - Name: country
            AttributeDataType: String
            #groupName
          - Name: group
            AttributeDataType: String
            Required: false
            #Date of Birth
          - Name: birthdate
            Required: false
        Policies:
          PasswordPolicy:
            MinimumLength: 6 

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: client-16
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"                        

